kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: typecheck
    image: registry.local.tylerangelier.com/oven/bun:1.3.11
    commands:
      - bun install --frozen-lockfile
      - bunx tsc --noEmit
    when:
      event:
        - push
        - pull_request

  - name: test
    image: registry.local.tylerangelier.com/oven/bun:1.3.11
    commands:
      - apt-get update && apt-get install -y git
      - bun install --frozen-lockfile
      - bun test
    when:
      event:
        - push
        - pull_request

  - name: build-linux
    image: registry.local.tylerangelier.com/oven/bun:1.3.11
    commands:
      - bun install --frozen-lockfile
      - bun run build:linux-x64
    when:
      event:
        - push
      branch:
        - main

  - name: build-darwin
    image: registry.local.tylerangelier.com/oven/bun:1.3.11
    commands:
      - bun install --frozen-lockfile
      - bun run build:darwin-arm64
    when:
      event:
        - push
      branch:
        - main
